name: E-commerce Test
run-name: ${{ github.actor }} is testing out GitHub Actions 

on:
  workflow_dispatch:
    inputs:
      branch: 
        default: 'main'
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        
      - name: Install dependencies
        run: npm install  

      - name: Run tests
        run: npx codeceptjs run --grep '@buyproduct'  
